{'actorCount': 1, 'actors': [{'name': '14 Karat Soul', 'url': '/celebrity/14_karat_soul',
                              'image': 'https://staticv2-4.rottentomatoes.com/static/images/redesign/poster_default_redesign.gif'}],
 'criticCount': 0, 'critics': [], 'franchiseCount': 0, 'franchises': [], 'movieCount': 128, 'movies': [
    {'name': '1492: Conquest of Paradise', 'year': 1992, 'url': '/m/1492_conquest_of_paradise',
     'image': 'https://resizing.flixster.com/yL9doTPdCIAvspEgs2YmveQh9vA=/fit-in/80x80/v1.bTsxMTIwNDczNTtqOzE4NjI0OzEyMDA7MTUxNTsyMDIw',
     'meterClass': 'rotten', 'meterScore': 32,
     'castItems': [{'name': 'G�rard Depardieu', 'url': '/celebrity/gerard_depardieu_2'},
                   {'name': 'Armand Assante', 'url': '/celebrity/armand_assante'},
                   {'name': 'Sigourney Weaver', 'url': '/celebrity/sigourney_weaver'}],
     'subline': 'G�rard Depardieu, Armand Assante, Sigourney Weaver, '},
    {'name': '11:14', 'year': 2003, 'url': '/m/1114',
     'image': 'https://resizing.flixster.com/7sLQ7TP8iGS8RJ_M-PRlP-5yrS0=/fit-in/80x80/v1.bTsxMTYxNDc2MTtqOzE4NjI5OzEyMDA7NzA4Ozk0NA',
     'meterClass': 'fresh', 'meterScore': 92, 'castItems': [{'name': 'Henry Thomas', 'url': '/celebrity/henry_thomas'},
                                                            {'name': 'Blake Heron', 'url': '/celebrity/blake_heron'},
                                                            {'name': 'Barbara Hershey',
                                                             'url': '/celebrity/barbara_hershey'}],
     'subline': 'Henry Thomas, Blake Heron, Barbara Hershey, '}, {'name': '1408', 'year': 2007, 'url': '/m/1408',
                                                                  'image': 'https://resizing.flixster.com/OYU5ai0rOh0dfEZqCFlHGSRbF9I=/fit-in/80x80/v1.bTsxMTI5NzQ4NztqOzE4NjI1OzEyMDA7MTUyMTsyMDI4',
                                                                  'meterClass': 'certified_fresh', 'meterScore': 80,
                                                                  'castItems': [{'name': 'John Cusack',
                                                                                 'url': '/celebrity/john_cusack'},
                                                                                {'name': 'Samuel L. Jackson',
                                                                                 'url': '/celebrity/samuel_l_jackson'},
                                                                                {'name': 'Mary McCormack',
                                                                                 'url': '/celebrity/mary_mccormack'}],
                                                                  'subline': 'John Cusack, Samuel L. Jackson, Mary McCormack, '},
    {'name': '14 Hours', 'year': 1951, 'url': '/m/14_hours',
     'image': 'https://resizing.flixster.com/JzKwiosjg_YB2QFwaDPh76Xg7tU=/fit-in/80x80/v1.bTsxMTI5OTM3NDtqOzE4NjI1OzEyMDA7MTMzNTsxNzgw',
     'meterClass': 'fresh', 'meterScore': 100,
     'castItems': [{'name': 'Richard Basehart', 'url': '/celebrity/richard_basehart'},
                   {'name': 'Paul Douglas', 'url': '/celebrity/paul_douglas'},
                   {'name': 'Barbara Bel Geddes', 'url': '/celebrity/barbara_bel_geddes'}],
     'subline': 'Richard Basehart, Paul Douglas, Barbara Bel Geddes, '},
    {'name': '14 Hours', 'year': 2005, 'url': '/m/14-hours',
     'image': 'https://resizing.flixster.com/ywqh24TBt2vFZpqR76qFmynEBjo=/fit-in/80x80/v1.bTsxMTcwMzgwNTtqOzE4NTQwOzEyMDA7MzkzOzU1OA',
     'meterClass': 'N/A', 'castItems': [{'name': 'JoBeth Williams', 'url': '/celebrity/jobeth_williams'},
                                        {'name': 'Rick Schroder', 'url': '/celebrity/rick_schroder'},
                                        {'name': 'Kris Kristofferson', 'url': '/celebrity/kris_kristofferson'}],
     'subline': 'JoBeth Williams, Rick Schroder, Kris Kristofferson, '},
    {'name': '14 Kil�metros (14 Kilometers)', 'year': 2007, 'url': '/m/14-kilometros',
     'image': 'https://staticv2-4.rottentomatoes.com/static/images/redesign/poster_default_redesign.gif',
     'meterClass': 'N/A', 'castItems': [{'name': 'Adoum Moussa', 'url': '/celebrity/adoum_moussa'},
                                        {'name': 'Illiassou Mahamadou Alzouma',
                                         'url': '/celebrity/illiassou_mahamadou_alzouma'},
                                        {'name': 'Aminata Kanta', 'url': '/celebrity/aminata_kanta'}],
     'subline': 'Adoum Moussa, Illiassou Mahamadou Alzouma, Aminata Kanta, '},
    {'name': 'Bruno', 'year': 2009, 'url': '/m/bruno',
     'image': 'https://resizing.flixster.com/C8BYoWpaZDHjUY5HQ5zKzcmecNY=/fit-in/80x80/v1.bTsxMTMxMTI3ODtqOzE4NjI1OzEyMDA7MjE2NjsyODg4',
     'meterClass': 'fresh', 'meterScore': 67,
     'castItems': [{'name': 'Sacha Baron Cohen', 'url': '/celebrity/sacha_baron_cohen'},
                   {'name': 'Gustaf Hammarsten', 'url': '/celebrity/gustaf_hammarsten'},
                   {'name': 'Paula Abdul', 'url': '/celebrity/paula_abdul'}],
     'subline': 'Sacha Baron Cohen, Gustaf Hammarsten, Paula Abdul, '},
    {'name': '14 Blades', 'year': 2014, 'url': '/m/14_blades',
     'image': 'https://resizing.flixster.com/JKKHQ6IVfU5lrUhenJ58KGgfUTo=/fit-in/80x80/v1.bTsxMTE3OTg5NTtqOzE4NjI0OzEyMDA7MTUwMDsyMzU0',
     'meterClass': 'fresh', 'meterScore': 69, 'castItems': [{'name': 'Donnie Yen', 'url': '/celebrity/donnie_yen'},
                                                            {'name': 'Wei Zhao', 'url': '/celebrity/vicki_zhao'},
                                                            {'name': 'Chun Wu', 'url': '/celebrity/chun_wu'}],
     'subline': 'Donnie Yen, Wei Zhao, Chun Wu, '}, {'name': 'Fourteen', 'year': 2020, 'url': '/m/fourteen_2019',
                                                     'image': 'https://resizing.flixster.com/bMVLj6-IYy0b0N1Lm_SQrd783IU=/fit-in/80x80/v1.bTsxMzQ0NjY2MjtqOzE4NjA1OzEyMDA7MzAwMDs0Mjcx',
                                                     'meterClass': 'certified_fresh', 'meterScore': 98, 'castItems': [
            {'name': 'Tallie Medel', 'url': '/celebrity/tallie_medel'},
            {'name': 'Norma Kuhling', 'url': '/celebrity/norma_kuhling'},
            {'name': 'C. Mason Wells', 'url': '/celebrity/c-mason-wells'}],
                                                     'subline': 'Tallie Medel, Norma Kuhling, C. Mason Wells, '}],
 'tvCount': 1, 'tvSeries': [
    {'title': 'Big Brother 14', 'startYear': 2012, 'endYear': 2012, 'url': '/tv/big_brother-CBS-1-2-3/s14',
     'meterClass': 'N/A',
     'image': 'https://resizing.flixster.com/Knxleq5w2UMO0nXXpmJCTAPTxr0=/fit-in/80x80/v1.dDsyNzY5NDI7ajsxODU2MDsxMjAwOzExMDA7ODI1'}]}
